[project]
name = "logparser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "geopy>=2.4.1",
    "matplotlib>=3.10.6",
    "pandas>=2.3.3",
    "pyqt5>=5.15.11",
    "scipy>=1.16.3",
    "seaborn>=0.13.2",
]
